### PR TITLE
Upgrade fluent-bit and metricbeat

### PR DESCRIPTION
**Pull request by SaaldjorMike**

### CODE REVIEW

**Review by ssboisen — APPROVED** [review]
LGTM - any chance we can test it before merge though considering we’re jumpint major versions

**Review by schofield — APPROVED** [review]

**Comment by schofield** [comment]
@ssboisen I tested this a lot today and it looks good. 

@SaaldjorMike Do you think we could merge in the HEC work (#126 ) so we don't have to just release another version. #126 is ready to go and was tested on dev-1 with a rebase off your changes on my personal fork.

**Review by jswoods — APPROVED** [review]

**Comment by SaaldjorMike** [comment]
> @SaaldjorMike Do you think we could merge in the HEC work (#126 ) so we don't have to just release another version.

Sure, we can do that. I'll update this PR such that it doesn't include the new release, then we can do that when merging #126.

**Comment by SaaldjorMike** [comment]
> LGTM - any chance we can test it before merge though considering we’re jumpint major versions

Similar to @schofield I also ran a couple of tests with these versions last week.

**Pull request merged**
